server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
  jpa:
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
      hibernate:
        default_schema: cm
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
info:
  version: @project.version@
  stage: dev
